// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUkxuMO_eTdsdGWTttiOdkM0_VeC2Jf2M',
    appId: '1:1049373965796:web:e66db85c0f77f29ae2dbf1',
    messagingSenderId: '1049373965796',
    projectId: 'health-monitor-41611',
    authDomain: 'health-monitor-41611.firebaseapp.com',
    storageBucket: 'health-monitor-41611.firebasestorage.app',
    measurementId: 'G-GQ5K4L9RX0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFhBi6UrGr0JM5t5JxouT203_x4p1fTFk',
    appId: '1:1049373965796:android:311259813951a0d0e2dbf1',
    messagingSenderId: '1049373965796',
    projectId: 'health-monitor-41611',
    storageBucket: 'health-monitor-41611.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjuvH6R3xFNJIwJJgUmH-ja47cknexsOE',
    appId: '1:1049373965796:ios:8ddb572a7ecaecb4e2dbf1',
    messagingSenderId: '1049373965796',
    projectId: 'health-monitor-41611',
    storageBucket: 'health-monitor-41611.firebasestorage.app',
    iosBundleId: 'com.example.healthMonitor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjuvH6R3xFNJIwJJgUmH-ja47cknexsOE',
    appId: '1:1049373965796:ios:8ddb572a7ecaecb4e2dbf1',
    messagingSenderId: '1049373965796',
    projectId: 'health-monitor-41611',
    storageBucket: 'health-monitor-41611.firebasestorage.app',
    iosBundleId: 'com.example.healthMonitor',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUkxuMO_eTdsdGWTttiOdkM0_VeC2Jf2M',
    appId: '1:1049373965796:web:8470274e9c117a7fe2dbf1',
    messagingSenderId: '1049373965796',
    projectId: 'health-monitor-41611',
    authDomain: 'health-monitor-41611.firebaseapp.com',
    storageBucket: 'health-monitor-41611.firebasestorage.app',
    measurementId: 'G-7C9ND6E0BV',
  );
}
