# Generated by Django 6.0.2 on 2026-02-22 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('postal_code', models.IntegerField()),
                ('preferred_language', models.CharField(choices=[('English', 'English'), ('Hindi', 'हिन्दी'), ('Marathi', 'मराठी')], default='English', max_length=20)),
                ('land_area_hectares', models.FloatField()),
                ('soil_type', models.CharField(choices=[('Clay', 'Clay Soil'), ('Sandy', 'Sandy Soil'), ('Loamy', 'Loamy Soil'), ('Mixed', 'Mixed Soil')], max_length=20)),
                ('experience_level', models.CharField(choices=[('Beginner', 'Beginner (New Farmer)'), ('Intermediate', 'Intermediate (2-5 years)'), ('Expert', 'Expert (5+ years)')], max_length=20)),
                ('farming_notes', models.TextField(blank=True)),
                ('contact_method', models.CharField(default='WhatsApp', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Farmer',
                'verbose_name_plural': 'Farmers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FarmerInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('item_type', models.CharField(choices=[('Seeds', 'Seeds'), ('Fertilizer', 'Fertilizer'), ('Pesticide', 'Pesticide'), ('Tools', 'Tools'), ('Water', 'Water'), ('Other', 'Other')], max_length=20)),
                ('quantity', models.FloatField()),
                ('unit', models.CharField(default='kg', max_length=20)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='farmers.farmer')),
            ],
            options={
                'verbose_name': 'Farmer Inventory',
                'verbose_name_plural': 'Farmer Inventory',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FarmerCrop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planting_date', models.DateField()),
                ('expected_harvest_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Planned', 'Planned'), ('Growing', 'Growing'), ('Harvested', 'Harvested'), ('Completed', 'Completed')], default='Planned', max_length=20)),
                ('area_allocated_hectares', models.FloatField()),
                ('expected_yield_kg', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farmers_growing_crop', to='crops.crop')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farmer_crops', to='farmers.farmer')),
            ],
            options={
                'verbose_name': 'Farmer Crop',
                'verbose_name_plural': 'Farmer Crops',
                'ordering': ['-planting_date'],
                'unique_together': {('farmer', 'crop', 'planting_date')},
            },
        ),
    ]
