# Generated by Django 6.0.3 on 2026-04-23 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0002_crop_crops_crop_name_a88701_idx_and_more'),
        ('farmers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='preferred_language',
            field=models.CharField(choices=[('English', 'English'), ('Hindi', 'à¤¹à¤¿à¤¨à¥\x8dà¤¦à¥€'), ('Marathi', 'à¤®à¤°à¤¾à¤\xa0à¥€')], default='English', max_length=20),
        ),
        migrations.AddIndex(
            model_name='farmer',
            index=models.Index(fields=['first_name'], name='farmers_far_first_n_40f846_idx'),
        ),
        migrations.AddIndex(
            model_name='farmer',
            index=models.Index(fields=['last_name'], name='farmers_far_last_na_2ce36c_idx'),
        ),
        migrations.AddIndex(
            model_name='farmer',
            index=models.Index(fields=['city'], name='farmers_far_city_47e829_idx'),
        ),
        migrations.AddIndex(
            model_name='farmercrop',
            index=models.Index(fields=['farmer'], name='farmers_far_farmer__a56fa7_idx'),
        ),
        migrations.AddIndex(
            model_name='farmercrop',
            index=models.Index(fields=['status'], name='farmers_far_status_928f35_idx'),
        ),
        migrations.AddIndex(
            model_name='farmercrop',
            index=models.Index(fields=['planting_date'], name='farmers_far_plantin_c936a1_idx'),
        ),
        migrations.AddIndex(
            model_name='farmerinventory',
            index=models.Index(fields=['farmer'], name='farmers_far_farmer__e5e317_idx'),
        ),
        migrations.AddIndex(
            model_name='farmerinventory',
            index=models.Index(fields=['item_type'], name='farmers_far_item_ty_284593_idx'),
        ),
        migrations.AddIndex(
            model_name='farmerinventory',
            index=models.Index(fields=['expiry_date'], name='farmers_far_expiry__2c1339_idx'),
        ),
    ]
