# Generated by Django 6.0.2 on 2026-02-22 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farmers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('temperature', models.FloatField()),
                ('humidity', models.IntegerField()),
                ('rainfall', models.IntegerField()),
                ('condition', models.CharField(choices=[('Sunny', 'Sunny'), ('Cloudy', 'Cloudy'), ('Rainy', 'Rainy'), ('Stormy', 'Stormy'), ('Partly Cloudy', 'Partly Cloudy')], max_length=20)),
                ('wind_speed', models.FloatField(default=0)),
                ('recorded_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Weather Data',
                'verbose_name_plural': 'Weather Data',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='FarmersWeatherAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_title', models.CharField(max_length=200)),
                ('alert_message', models.TextField()),
                ('severity', models.CharField(choices=[('Low', 'Low - Minor'), ('Medium', 'Medium - Moderate'), ('High', 'High - Serious'), ('Critical', 'Critical - Severe')], max_length=20)),
                ('alert_type', models.CharField(choices=[('Rain', 'Heavy Rain'), ('Frost', 'Frost/Cold'), ('Heat', 'Extreme Heat'), ('Wind', 'Strong Wind'), ('Disease', 'Disease Risk'), ('Pest', 'Pest Alert')], max_length=20)),
                ('issued_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('action_taken', models.BooleanField(default=False)),
                ('farmer_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_alerts', to='farmers.farmer')),
            ],
            options={
                'verbose_name': 'Weather Alert',
                'verbose_name_plural': 'Weather Alerts',
                'ordering': ['-issued_at'],
            },
        ),
        migrations.CreateModel(
            name='WeatherForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('forecast_date', models.DateField()),
                ('min_temperature', models.FloatField()),
                ('max_temperature', models.FloatField()),
                ('rainfall_probability', models.IntegerField()),
                ('expected_rainfall_mm', models.IntegerField(default=0)),
                ('humidity', models.IntegerField()),
                ('condition', models.CharField(choices=[('Sunny', 'Sunny'), ('Cloudy', 'Cloudy'), ('Rainy', 'Rainy'), ('Stormy', 'Stormy'), ('Partly Cloudy', 'Partly Cloudy')], max_length=20)),
                ('wind_speed', models.FloatField(default=0)),
                ('forecast_issued_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Weather Forecast',
                'verbose_name_plural': 'Weather Forecasts',
                'ordering': ['forecast_date'],
                'unique_together': {('location', 'forecast_date')},
            },
        ),
    ]
