# Generated by Django 6.0.3 on 2026-04-26 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmersweatheralert',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='farmersweatheralert',
            name='region',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
