// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIXAiNC0qKQDkt5G-XaQj0hFAN4MCrEl8',
    appId: '1:369807633070:web:b0cf0378d9ee167154db3f',
    messagingSenderId: '369807633070',
    projectId: 'coffee-1919',
    authDomain: 'coffee-1919.firebaseapp.com',
    storageBucket: 'coffee-1919.firebasestorage.app',
    measurementId: 'G-45HZ2TR4TK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXV76zEvm3YyB1vka0SrAF2FFx8ec3B08',
    appId: '1:369807633070:android:c78e400e71f9873a54db3f',
    messagingSenderId: '369807633070',
    projectId: 'coffee-1919',
    storageBucket: 'coffee-1919.firebasestorage.app',
  );
}
