# Generated by Django 6.0.2 on 2026-02-22 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('season', models.CharField(choices=[('Kharif', 'Kharif (Monsoon)'), ('Rabi', 'Rabi (Winter)'), ('Summer', 'Summer')], default='Kharif', max_length=20)),
                ('soil_type', models.CharField(choices=[('Clay', 'Clay Soil'), ('Sandy', 'Sandy Soil'), ('Loamy', 'Loamy Soil'), ('Mixed', 'Mixed Soil')], max_length=20)),
                ('growth_duration_days', models.IntegerField()),
                ('optimal_temperature', models.FloatField()),
                ('optimal_humidity', models.FloatField()),
                ('optimal_soil_moisture', models.FloatField()),
                ('water_required_mm_per_week', models.FloatField(default=25)),
                ('fertilizer_required', models.CharField(default='NPK', max_length=200)),
                ('expected_yield_per_hectare', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Crop',
                'verbose_name_plural': 'Crops',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CropCareTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('recommended_dap', models.IntegerField()),
                ('frequency', models.CharField(default='Once', max_length=50)),
                ('instructions', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='care_tasks', to='crops.crop')),
            ],
            options={
                'verbose_name': 'Care Task',
                'verbose_name_plural': 'Care Tasks',
                'ordering': ['crop', 'recommended_dap'],
            },
        ),
        migrations.CreateModel(
            name='CropGrowthStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_name', models.CharField(max_length=100)),
                ('duration_days', models.IntegerField()),
                ('stage_number', models.IntegerField()),
                ('optimal_temperature', models.FloatField()),
                ('optimal_humidity', models.FloatField()),
                ('optimal_soil_moisture', models.FloatField()),
                ('description', models.TextField(blank=True)),
                ('care_instructions', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='growth_stages', to='crops.crop')),
            ],
            options={
                'verbose_name': 'Growth Stage',
                'verbose_name_plural': 'Growth Stages',
                'ordering': ['crop', 'stage_number'],
            },
        ),
        migrations.CreateModel(
            name='CropGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sowing_instructions', models.TextField()),
                ('watering_schedule', models.TextField()),
                ('watering_days_interval', models.IntegerField(default=7)),
                ('fertilizer_schedule', models.TextField()),
                ('disease_management', models.TextField()),
                ('pest_management', models.TextField()),
                ('harvesting_instructions', models.TextField()),
                ('storage_instructions', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guides', to='crops.crop')),
            ],
            options={
                'verbose_name': 'Crop Guide',
                'verbose_name_plural': 'Crop Guides',
            },
        ),
        migrations.CreateModel(
            name='CropRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommended_season', models.CharField(choices=[('Kharif', 'Kharif'), ('Rabi', 'Rabi'), ('Summer', 'Summer')], max_length=20)),
                ('recommendation_reason', models.TextField()),
                ('priority_score', models.IntegerField(default=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='crops.crop')),
            ],
            options={
                'verbose_name': 'Crop Recommendation',
                'verbose_name_plural': 'Crop Recommendations',
                'ordering': ['-priority_score'],
            },
        ),
    ]
