# Generated by Django 6.0.3 on 2026-04-23 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='crop',
            index=models.Index(fields=['name'], name='crops_crop_name_a88701_idx'),
        ),
        migrations.AddIndex(
            model_name='crop',
            index=models.Index(fields=['season'], name='crops_crop_season_c259d7_idx'),
        ),
        migrations.AddIndex(
            model_name='crop',
            index=models.Index(fields=['soil_type'], name='crops_crop_soil_ty_213c26_idx'),
        ),
    ]
