# Generated by Django 6.0.3 on 2026-04-23 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0002_crop_crops_crop_name_a88701_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='category',
            field=models.CharField(choices=[('Cereal', 'Cereal'), ('Pulse', 'Pulse'), ('Oilseed', 'Oilseed'), ('Vegetable', 'Vegetable'), ('Fruit', 'Fruit'), ('Fodder', 'Fodder'), ('Other', 'Other')], default='Other', max_length=20),
        ),
        migrations.AddField(
            model_name='crop',
            name='crop_type',
            field=models.CharField(choices=[('Field', 'Field Crop'), ('Horticulture', 'Horticulture'), ('Plantation', 'Plantation'), ('Greenhouse', 'Greenhouse'), ('Other', 'Other')], default='Field', max_length=20),
        ),
        migrations.AddIndex(
            model_name='crop',
            index=models.Index(fields=['category'], name='crops_crop_categor_7f15f6_idx'),
        ),
        migrations.AddIndex(
            model_name='crop',
            index=models.Index(fields=['crop_type'], name='crops_crop_crop_ty_cec7ed_idx'),
        ),
    ]
