# Generated by Django 6.0.3 on 2026-04-26 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0003_crop_category_crop_crop_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='states',
            field=models.CharField(blank=True, default='', help_text='Comma-separated states where this crop grows. e.g. Maharashtra,Punjab,Gujarat', max_length=500),
        ),
        migrations.AddIndex(
            model_name='crop',
            index=models.Index(fields=['states'], name='crops_crop_states_0b3dab_idx'),
        ),
    ]
