# Generated by Django 6.0.2 on 2026-02-22 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crops', '0001_initial'),
        ('farmers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmerTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=100)),
                ('task_description', models.TextField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Overdue', 'Overdue'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20)),
                ('due_date', models.DateField()),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('priority', models.IntegerField(default=5)),
                ('importance', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], default='Medium', max_length=20)),
                ('is_completed', models.BooleanField(default=False)),
                ('reminder_sent_at', models.DateTimeField(blank=True, null=True)),
                ('farmer_notes', models.TextField(blank=True)),
                ('photo_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('care_task_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='farmer_tasks', to='crops.cropcaretask')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='farmers.farmer')),
                ('farmer_crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='farmers.farmercrop')),
            ],
            options={
                'verbose_name': 'Farmer Task',
                'verbose_name_plural': 'Farmer Tasks',
                'ordering': ['due_date', '-importance'],
            },
        ),
        migrations.CreateModel(
            name='TaskLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('Created', 'Task Created'), ('Started', 'Task Started'), ('Progress', 'Progress Update'), ('Completed', 'Task Completed'), ('Updated', 'Task Updated'), ('Cancelled', 'Task Cancelled')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.CharField(blank=True, max_length=500)),
                ('performed_by_farmer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_action_logs', to='farmers.farmer')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='tasks.farmertask')),
            ],
            options={
                'verbose_name': 'Task Log',
                'verbose_name_plural': 'Task Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='TaskReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_channel', models.CharField(choices=[('SMS', 'SMS (Text Message)'), ('WhatsApp', 'WhatsApp'), ('App', 'App Notification'), ('Email', 'Email')], max_length=20)),
                ('reminder_date', models.DateField()),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('is_sent', models.BooleanField(default=False)),
                ('reminder_message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='tasks.farmertask')),
            ],
            options={
                'verbose_name': 'Task Reminder',
                'verbose_name_plural': 'Task Reminders',
                'ordering': ['reminder_date'],
            },
        ),
    ]
