# Generated by Django 6.0.3 on 2026-04-23 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0002_crop_crops_crop_name_a88701_idx_and_more'),
        ('farmers', '0002_alter_farmer_preferred_language_and_more'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='farmertask',
            index=models.Index(fields=['farmer'], name='tasks_farme_farmer__2d457a_idx'),
        ),
        migrations.AddIndex(
            model_name='farmertask',
            index=models.Index(fields=['status'], name='tasks_farme_status_52ec94_idx'),
        ),
        migrations.AddIndex(
            model_name='farmertask',
            index=models.Index(fields=['due_date'], name='tasks_farme_due_dat_32e4db_idx'),
        ),
        migrations.AddIndex(
            model_name='tasklog',
            index=models.Index(fields=['task'], name='tasks_taskl_task_id_a26fb7_idx'),
        ),
        migrations.AddIndex(
            model_name='tasklog',
            index=models.Index(fields=['action'], name='tasks_taskl_action_fcf8d3_idx'),
        ),
        migrations.AddIndex(
            model_name='tasklog',
            index=models.Index(fields=['timestamp'], name='tasks_taskl_timesta_ab1a25_idx'),
        ),
        migrations.AddIndex(
            model_name='taskreminder',
            index=models.Index(fields=['task'], name='tasks_taskr_task_id_d5ee59_idx'),
        ),
        migrations.AddIndex(
            model_name='taskreminder',
            index=models.Index(fields=['reminder_date'], name='tasks_taskr_reminde_ba9950_idx'),
        ),
        migrations.AddIndex(
            model_name='taskreminder',
            index=models.Index(fields=['is_sent'], name='tasks_taskr_is_sent_f79672_idx'),
        ),
    ]
