# Generated by Django 6.0.3 on 2026-04-26 03:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0002_alter_farmer_preferred_language_and_more'),
        ('tasks', '0002_farmertask_tasks_farme_farmer__2d457a_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('reminder_type', models.CharField(choices=[('pending', 'Pending'), ('overdue', 'Overdue'), ('custom', 'Custom')], max_length=20)),
                ('farmers', models.ManyToManyField(related_name='reminders', to='farmers.farmer')),
                ('sent_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
    ]
